### PR TITLE
Remove flaky eunit test

### PR DESCRIPTION
**Pull request by nickva**
COUCHDB-2848

### CODE REVIEW

**Comment by davisp** [comment]
You should remove dict_fetch as well. Also you should note in your commit message that we're removing it because its just a race to prove its faster than dict which is now well established and we can remove it due to it causing test failures in a few instances.

Otherwise +1

**Comment by kxepal** [comment]
Removing so brute is not a good idea since we loose information about KHash performance. These tests ensures that KHash is faster than Dict and that's the point.

We need either:
1. Investigate when KHash starts to be slower and why. I'm on the same as @mar-ia environment cannot reproduce that failure.
2. If first option is not possible/not enough of time/boring/lazy/etc move these tests into benchmark script which runs with `make check` command. It won't get triggered by rebar, but will be used for local development.

**Comment by davisp** [comment]
@kxepal I think its well established that its faster. I only wrote that test when I was developing khash to prove it to myself. Since then the performance has been demonstrated rather extensively by couch_event and friends.

Also if we wanted to get into an actual performance check we should probably look at something like basho_bench definitions that actually do an analysis as the average over a bunch of operations is basically "How not to Performance Test 101".

**Comment by kxepal** [comment]
@davisp It's so now, but may be not tomorrow (: 
We can find a lot of ways to improve this test to make it more precisely, but now it plays well to prove that khash is faster. How much is a another story.

**Comment by nickva** [comment]
@davisp : removed dict_fetch and explained more in the commit message.

**Comment by davisp** [comment]
@kxepal I really don't think its worth investing that much time in this code. Its both a terrible unit test and performance test because its really neither of those things. If we want to design a benchmark for doing performance testing on various key/value modules that could be quite useful though I think is quite beyond the scope of this PR.

**Comment by kxepal** [comment]
@davisp My point is that better keep something than have nothing, while we can always improve things later. But you're the boss (:

**Pull request merged**
