### PR TITLE
Change minimum Erlang to OTP 19

### PR DESCRIPTION
**Pull request by jaydoane**

### CODE REVIEW

**Review by iilyak — APPROVED** [review]
+1

**Comment by iilyak** [comment]
I know I already approved the PR. I would appreciate if we can remove `test/khash_rand.erl` file as part of this PR.

**Comment by jaydoane** [comment]
@iilyak I've removed test/khash_rand.erl and refactored to use direct `rand:uniform` calls.

**Review by iilyak — APPROVED** [review]
+1

**Pull request merged**
